/*
 * Contact Management API
 *
 * This is a Contact Management API, developed as part of InvestorFlow technical assessment.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: karanparmar0130@gmail.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System.ComponentModel.DataAnnotations;
using Asp.Versioning;
using InvestorFlow.ContactManagement.API.Attributes;
using InvestorFlow.ContactManagement.API.Models;
using InvestorFlow.ContactManagement.Application.Interfaces;
using Microsoft.AspNetCore.Mvc;
using DomainContact = InvestorFlow.ContactManagement.Domain.Entities.Contact;

namespace InvestorFlow.ContactManagement.API.Controllers
{
    /// <summary>
    /// Fund Controller Definition
    /// </summary>
    [ApiController]
    [Route("/api/v{version:apiVersion}/fund")]
    [ApiVersion("1")]
    [ValidateModelState]
    public class FundController(
        ILogger<FundController> logger,
        IFundService fundService,
        IMapper<IEnumerable<DomainContact>, FundResponse> contactResponseMapper) : ControllerBase
    {
        /// <summary>
        /// Find contacts for a fund
        /// </summary>
        /// <remarks>Returns a list of contacts</remarks>
        /// <param name="fundId">Id of fund</param>
        /// <response code="200">Successful operation</response>
        /// <response code="400">Invalid Id supplied</response>
        /// <response code="404">Contact not found</response>
        /// <response code="500">Server exception</response>
        [HttpGet("{fundId}/contacts")]
        [MapToApiVersion("1")]
        public async Task<IActionResult> GetContactsForFund(
            [FromRoute] [Required] Guid fundId)
        {
            var serviceResponse = await fundService.ListContactsForFundAsync(fundId);
            var contactResponse = contactResponseMapper.Map(serviceResponse);

            logger.LogInformation("List contacts for fund completed");
            return Ok(contactResponse);
        }
    }
}
